### ISSUE TITLE
invisible armours

### ISSUE THREAD

**Issue by superon** [Draylar/wolves-with-armor#15] opened 2020-11-12 17:16 UTC
seems these become invisible on player death

**Comment by Draylar** [comment] 2020-11-12 21:34
[Can't reproduce.](https://streamable.com/pqje9w) Can you send a game log and tell me how to reproduce the issue?

**Comment by superon** [comment] 2020-11-12 22:50
seems to be a compatibility issue with Origins.
running:
fabric-api-0.25.4+1.16
Origins-1.16.4-0.4.4
wolves-with-armor-1.5.2-1.16.2

maybe i'm hoping for too much from a mod not made for 1.16.4 :/

**Comment by bdamitz** [comment] 2021-02-26 21:03
Can confirm problem with Origins. Can reproduce running:
fabric-api-0.31.0+1.16
immersive-portals-0.80-mc1.16.5-fabric
Origins-1.16.5-0.5.1
Origins-Classes-1.16.5-1.1.1
PetOwner-1.7.1-1.16.2+
respawnablepets-1.16.5-1
wolves-with-armor-1.5.2-1.16.2

Armors play nicely with other mods (PetOwner, respawnablepets), but not Origins. Horse armors show no issue with Origins though, normal visibility/respawn.

Side note for respawnablepets: the armor also becomes invisible when the wolf (not player) respawns with Origins. Without Origins and with respawnablepets, armor is respawned as well.

**Comment by Cognizaunce** [comment] 2021-03-10 05:09
I run a server, and the glitch works slightly differently. Everything works fine at the start, but once I stop my server for the day and reload it the next day, all the armors become invisible. They still work mind you, as I can't make my wolves receive armor. Speaking of which, is there a way to remove armor from a dog?

**Comment by Cognizaunce** [comment] 2021-03-10 05:36
Here are my mods.

audiooutput-1.16.2-0.0.3.jar
caelus-fabric-0.0.15-1.16.4.jar
cloth-config-4.11.14-fabric.jar
curios-fabric-0.0.11-1.16.4.jar
curiouselytra-fabric-1.1.1-1.16.5.jar
DynamicSoundFilters-1.2.0+1.16.5.jar
EditSign-Fabric-1.16.5-2.2.0.jar
fabric-api-0.31.0+1.16.jar
fabric-language-kotlin-1.4.30+build.2.jar
GameInfo-mod-2.0.1+1.16.4.jar
inmis-2.1.1-1.16.4.jar
lambdynamiclights-fabric-1.3.4+1.16.jar
lapisreserve-1.0.6.jar
lithium-fabric-mc1.16.5-0.6.4.jar
Mambience-2.1.0+1.16.4.jar
mobs-attempt-parkour-0.2.2-1.16.5.jar
modmenu-1.16.8.jar
netherite-horse-armor-1.1.0.jar
PetOwner-1.7.1-1.16.2+.jar
phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
PresenceFootsteps-r29+1.16.4.jar
reroll-1.2.0-1.16.5.jar
sodium-fabric-mc1.16.3-0.1.0.jar
wolves-with-armor-1.5.2-1.16.2.jar

**Comment by Cognizaunce** [comment] 2021-03-10 05:41
Oh. Looking through the closed issues I found you can shift click to remove armor. I downloaded your mod from curseforge, and the description does not give any detail how. It should be added there.

**Comment by Cognizaunce** [comment] 2021-03-10 23:36
Update: The armor becomes visible once I de-equip it, and then re-equip it. Maybe this will help if you get the same glitch.

**Comment by Draylar** [comment] 2021-03-10 23:47
I'll look into this in a bit, might be a CCA issue (my deps are pretty outdated), thanks for the info 👍

**Comment by Cognizaunce** [comment] 2021-05-08 13:46
After the new update it is fixed now. Thank you.

**Closed as completed** 2021-05-08 20:08 UTC
